name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: microsoft/fluentui-system-icons
        path: './fluentui-system-icons'
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./FluentIcons.Resources/FluentIcons.Resources.csproj
    - name: Install CS-Script
      run: repo=https://github.com/oleg-shilo/cs-script/releases/download/v4.4.7.0/; file=cs-script_4.4-7.deb; rm $file; wget $repo$file; sudo dpkg -i $file
    - name: Generate resources
      run: css .\resource_generate.cs
    - name: Build
      run: dotnet build --no-restore
