name: .NET NuGet Tag Release
on:
  push:
    tags:
    - 'v*'
  create:
    tags:
    - 'v*'

jobs:
  build:
    environment: NuGet
    env:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      NUGETAPI: ${{ secrets.NUGETAPI }}      
      GH_PACKAGES_APIKEY: ${{ secrets.GH_PACKAGES_APIKEY }}
      PACKAGESAPI: ${{ secrets.PACKAGESAPI }}
      NUGETCONFIG: ${{ secrets.NUGETCONFIG }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout fluentui-system-icons
      uses: actions/checkout@v3  
      with:
        repository: microsoft/fluentui-system-icons
        path: fluentui-system-icons
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore /home/runner/work/FluentIcons.Resources/FluentIcons.Resources/main/FluentIcons.Resources/FluentIcons.Resources.csproj
    - name: Install CS-Script
      run: repo=https://github.com/oleg-shilo/cs-script/releases/download/v4.4.7.0/; file=cs-script_4.4-7.deb; wget $repo$file; sudo dpkg -i $file; rm $file
    - name: Generate resources
      run: |
        cd /home/runner/work/FluentIcons.Resources/FluentIcons.Resources/main/GenerateResources
        css ./resource_generate.cs
    - name: Build
      run: dotnet build --no-restore /home/runner/work/FluentIcons.Resources/FluentIcons.Resources/main/FluentIcons.Resources/FluentIcons.Resources.csproj
    - name: Decode NuGet config
      run: |
        echo -n "$NUGETCONFIG" | base64 --decode > ./nuget.config
    - name: Push NuGets
      run: |
       for f in $(find ./ -name '*FluentIcons.Resources*.nupkg')
       do
         dotnet nuget push $f -k $GH_PACKAGES_APIKEY -s $PACKAGESAPI --skip-duplicate
         dotnet nuget push $f -k $NUGET_APIKEY -s $NUGETAPI --skip-duplicate
       done
